reverted image-number

diff --git a/hooks/post-command b/hooks/post-command
--- a/hooks/post-command
+++ b/hooks/post-command
@@ -18,8 +18,10 @@ else
     buildkite-agent annotate --style error --context exit_reason "${annotation}"
     exit 1
 fi
-if [ -n "${BUILDKITE_PLUGIN_ECR_SCAN_RESULTS_MAX_CRITICALS+x}" ]
+if [ -z "${BUILDKITE_PLUGIN_ECR_SCAN_RESULTS_MAX_CRITICALS+x}" ]
 then
+    MAX_CRITICALS="0"
+else
     MAX_CRITICALS="${BUILDKITE_PLUGIN_ECR_SCAN_RESULTS_MAX_CRITICALS}"
     if [[ ! "${MAX_CRITICALS}" =~ ${count_pattern} ]]
     then
@@ -27,11 +29,11 @@ then
         buildkite-agent annotate --style error --context exit_reason "${annotation}"
         exit 1
     fi
-else
-    MAX_CRITICALS="0"
 fi
-if [ -n "${BUILDKITE_PLUGIN_ECR_SCAN_RESULTS_MAX_HIGHS+x}" ]
+if [ -z "${BUILDKITE_PLUGIN_ECR_SCAN_RESULTS_MAX_HIGHS+x}" ]
 then
+    MAX_HIGHS="0"
+else
     MAX_HIGHS="${BUILDKITE_PLUGIN_ECR_SCAN_RESULTS_MAX_HIGHS}"
     if [[ ! "${MAX_HIGHS}" =~ ${count_pattern} ]]
     then
@@ -39,8 +41,18 @@ then
         buildkite-agent annotate --style error --context exit_reason "${annotation}"
         exit 1
     fi
+fi
+if [ -z "${BUILDKITE_PLUGIN_ECR_SCAN_RESULTS_IMAGE_NUMBER+x}" ]
+then
+    IMAGE_NUMBER=""
 else
-    MAX_HIGHS="0"
+    IMAGE_NUMBER="_${BUILDKITE_PLUGIN_ECR_SCAN_RESULTS_IMAGE_NUMBER}"
+    if [[ ! "${IMAGE_NUMBER}" =~ [1-9] ]]
+    then
+        annotation=$(printf "Error: value for IMAGE_NUMBER must be a single digit positive integer.\n")
+        buildkite-agent annotate --style error --context exit_reason "${annotation}"
+        exit 1
+    fi
 fi
 
 # print input values
@@ -94,7 +106,7 @@ case "${scan_status}" in
         ;;
     *)
         annotation=$(printf "Error: ECR vulnerability scan failed with status: %s\n" "${scan_status}")
-        buildkite-agent annotate --style error --context exit_reason "${annotation}"
+        buildkite-agent annotate --style error --context "exit_reason${IMAGE_NUMBER}" "${annotation}"
         exit 1
         ;;
 esac
@@ -102,7 +114,7 @@ esac
 # report results
 vuln_url=$(printf "https://%s.console.aws.amazon.com/ecr/repositories/private/%s/%s/image/%s/scan-results/?region=%s" "${REGION}" "${REPOSITORY_ID}" "${REPO_NAME}" "${image_digest}" "${REGION}")
 annotation=$(printf "%4d Critical vulnerabilities<br />%4d High vulnerabilities<br />Browse to <a href=\"%s\">image vulnerabilities</a> when logged into the appropriate AWS account with ecr:DescribeImages and ecr:DescribeImageScanFindings permissions" "${criticals}" "${highs}" "${vuln_url}")
-buildkite-agent annotate --style info --context vuln_counts "${annotation}"
+buildkite-agent annotate --style info --context "vuln_counts${IMAGE_NUMBER}" "${annotation}"
 
 # check if thresholds are exceeded and if so fail build
 fail_build="false"
@@ -119,6 +131,6 @@ then
 fi
 if  [ "${fail_build}" = "true" ]
 then
-    buildkite-agent annotate --style error --context fail_reason "${annotation}"
+    buildkite-agent annotate --style error --context "fail_reason${IMAGE_NUMBER}" "${annotation}"
     exit 1
 fi
