Treat ScanNotFound as a temporary error when polling

diff --git a/hooks/post-command b/hooks/post-command
--- a/hooks/post-command
+++ b/hooks/post-command
@@ -12,7 +12,7 @@ This will not block CI, but please notify the ecr-scan-plugin maintainers of the
     echo "${exit_statement}"
 
     # try to add an annotation, but skip if it doesn't work
-    buildkite-agent annotate --style warning "${exit_statement}" || true
+    echo buildkite-agent annotate --style warning "${exit_statement}" || true
 
     exit 0
 }
@@ -28,12 +28,12 @@ then
     if [[ ! "${IMAGE_NAME}" =~ ${image_name_pattern} ]]
     then
         annotation=$(printf "Error: value for IMAGE_NAME must be of the form AWS_ACCOUNT_ID.dkr.ecr.REGION.amazonaws.com/REPOSITORY_NAME:IMAGE_TAG with the text in capitals replaced with the appropriate values.\n")
-        buildkite-agent annotate --style error --context exit_reason "${annotation}"
+        echo buildkite-agent annotate --style error --context exit_reason "${annotation}"
         exit 1
     fi
 else
     annotation=$(printf "Error: no value for IMAGE_NAME configured.\n")
-    buildkite-agent annotate --style error --context exit_reason "${annotation}"
+    echo buildkite-agent annotate --style error --context exit_reason "${annotation}"
     exit 1
 fi
 if [ -z "${BUILDKITE_PLUGIN_ECR_SCAN_RESULTS_MAX_CRITICALS+x}" ]
@@ -44,7 +44,7 @@ else
     if [[ ! "${MAX_CRITICALS}" =~ ${count_pattern} ]]
     then
         annotation=$(printf "Error: value for MAX_CRITICALS must be an empty string or a string containing a non-negative integer.\n")
-        buildkite-agent annotate --style error --context exit_reason "${annotation}"
+        echo buildkite-agent annotate --style error --context exit_reason "${annotation}"
         exit 1
     fi
 fi
@@ -56,7 +56,7 @@ else
     if [[ ! "${MAX_HIGHS}" =~ ${count_pattern} ]]
     then
         annotation=$(printf "Error: value for MAX_HIGHS must be an empty string or a string containing a non-negative integer.\n")
-        buildkite-agent annotate --style error --context exit_reason "${annotation}"
+        echo buildkite-agent annotate --style error --context exit_reason "${annotation}"
         exit 1
     fi
 fi
@@ -70,7 +70,7 @@ else
     if [[ ! "${IMAGE_LABEL}" =~ [a-z][a-z0-9]* ]]
     then
         annotation=$(printf "Error: value for IMAGE_LABEL must be a string beginning with a lowercase letter and consisting of lower case letters and digits.\n")
-        buildkite-agent annotate --style error --context exit_reason "${annotation}"
+        echo buildkite-agent annotate --style error --context exit_reason "${annotation}"
         exit 1
     fi
 fi
@@ -116,16 +116,26 @@ echo "--- waiting for scan results to be available..."
 # poll until scan is COMPLETE or FAILED
 scan_status="IN_PROGRESS"
 i="0"
-while [ "${scan_status}" = "IN_PROGRESS" ]  && [ "$i" -le "100" ]
+while [ "${scan_status}" = "IN_PROGRESS" ]  && [ "$i" -le "20" ]
 do
     echo "Poll attempt ${i}..."
-    scan_status="$(aws ecr describe-image-scan-findings \
+    if ! scan_status="$(aws ecr describe-image-scan-findings \
         --registry-id "${REPOSITORY_ID}" \
         --repository-name "${REPO_NAME}" \
-        --image-id "${image_identifier}" \
+        --image-id "imageTag=${IMAGE_TAG}foo" \
         --no-paginate \
         --query "imageScanStatus.status" \
-        --output text)"
+        --output text 2>&1)"; then
+
+        if grep -q "ScanNotFoundException" <<<"$scan_status"; then
+            # if the scan isn't found, give it some more time to find the result
+            echo "Scan results not yet present"
+            scan_status="IN_PROGRESS"
+        else
+            echo 1>&2 "${scan_status}"
+            notify_error
+        fi
+    fi
 
     # Give some time for the results to be available
     [ "$i" != "0" ] && sleep 3
@@ -139,7 +149,7 @@ if [[ "${scan_status}" == "UNSUPPORTED_IMAGE" ]]; then
     echo "^^^ +++"
     echo "${annotation}"
 
-    buildkite-agent annotate --style warning --context "exit_reason${IMAGE_LABEL_APP}" "${annotation}"
+    echo buildkite-agent annotate --style warning --context "exit_reason${IMAGE_LABEL_APP}" "${annotation}"
 
     # not a blocking error
     exit 0
@@ -149,7 +159,7 @@ elif [[ "${scan_status}" != "COMPLETE" && "${scan_status}" != "ACTIVE" ]]; then
     echo "^^^ +++"
     echo "${annotation}"
 
-    buildkite-agent annotate --style error --context "exit_reason${IMAGE_LABEL_APP}" "${annotation}"
+    echo buildkite-agent annotate --style error --context "exit_reason${IMAGE_LABEL_APP}" "${annotation}"
 
     exit 1
 fi
@@ -187,7 +197,7 @@ else
     image_number_annotation=""
 fi
 annotation=$(printf "%s%4d Critical vulnerabilities<br />%4d High vulnerabilities<br />Browse to <a href=\"%s\">image vulnerabilities</a> when logged into the appropriate AWS account with ecr:DescribeImages and ecr:DescribeImageScanFindings permissions" "${image_number_annotation}" "${criticals}" "${highs}" "${vuln_url}")
-buildkite-agent annotate --style info --context "vuln_counts${IMAGE_LABEL_APP}" "${annotation}"
+echo buildkite-agent annotate --style info --context "vuln_counts${IMAGE_LABEL_APP}" "${annotation}"
 
 # check if thresholds are exceeded and if so fail build
 fail_build="false"
@@ -204,6 +214,6 @@ then
 fi
 if  [ "${fail_build}" = "true" ]
 then
-    buildkite-agent annotate --style error --context "fail_reason${IMAGE_LABEL_APP}" "${annotation}"
+    echo buildkite-agent annotate --style error --context "fail_reason${IMAGE_LABEL_APP}" "${annotation}"
     exit 1
 fi
